version: 2

multi-ecosystem-groups:
  main:
    schedule:
      interval: cron
      cronjob: 0 0 * * 0

updates:
  - package-ecosystem: github-actions
    multi-ecosystem-group: main
    patterns: ["*"]
    directory: /

  - package-ecosystem: gitsubmodule
    multi-ecosystem-group: main
    patterns: ["*"]
    directory: /
