name: Upgrade

on:
  schedule:
    - cron: "0 0 * * 6"

jobs:
  upgrade:
    name: Upgrade
    runs-on: ubuntu-latest

    container:
      image: archlinux

    permissions:
      contents: write

    steps:
      - name: Install packages
        run: pacman --noconfirm --sync --refresh --sysupgrade base-devel devtools nvchecker git github-cli

      - uses: actions/checkout@v6.0.3

      - name: Setup user
        run: |
          useradd --create-home user
          echo "user ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R user:user .

      - name: Upgrade
        run: |
          for pkg in */; do
            pkg="${pkg%/}"
            if [[ ! -f $pkg/PKGBUILD ]]; then continue; fi

            cd "$pkg"
            if [[ -f .nvchecker.toml ]]; then
              sudo -u user pkgctl version upgrade || true
            else
              sudo -u user makepkg --noconfirm --syncdeps --nobuild
            fi

            sudo -u user git add PKGBUILD
            cd ..
          done

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.PR_TOKEN }}
        run: |
          chown -R root:root .
          if ! git diff --staged --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            BRANCH="upgrade/$(date "+%F")"
            git checkout -b "$BRANCH"

            git commit --message "chore: upgrade"
            git push --set-upstream origin "$BRANCH"
            gh pr create --fill --base main --head "$BRANCH"
          fi
